spring.main.banner-mode=off

logging.level.root=INFO
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR
logging.level.com.netflix.eureka=ERROR
logging.level.com.netflix.discovery=ERROR
logging.level.com.EComMicroService=INFO


spring.application.name=PRODUCT-SERVICE

# spring.datasource.url=${DB_URL}/ECOMMERCE_DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ECOMMERCE_DB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# logging.level.org.springframework.security=DEBUG


spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.timeout=6000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8084

# Actuator & Monitoring
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=demo-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
