package com.EComMicroService.PaymentServices.Enums;

public enum EventType {
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_CANCELLED,
    ORDER_FAILED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    STOCK_RESERVED,
    STOCK_RESERVATION_FAILED,
    STOCK_RESERVATION_REVERSED,
    ORDER_COMPLETED
}