spring.main.banner-mode=off

logging.level.root=INFO
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR
logging.level.com.netflix.eureka=ERROR
logging.level.com.netflix.discovery=ERROR
logging.level.com.EComMicroService=INFO

spring.application.name=PAYMENT-SERVICE

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# spring.datasource.url=${DB_URL}/ECOMMERCE_DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ECOMMERCE_DB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8083